name: 'PR Validation'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@master
    secrets: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      subjectPattern: '^.+$'
