name: 'PR Validation'
permissions: write-all
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@fix/pr-checks
    secrets: 
      GITHUB_TOKEN: ${{ github.token }}
    with:
      subjectPattern: '^.+$'
